sudo: required
language: go

os:
  # - linux
  # - osx
  - windows

go:
  - 1.11.x

matrix:
  allow_failures:
    - os: windows

addons:
  homebrew:
    update: true
    packages:
    - socat
  apt:
    update: true
    packages:
    - socat

install:
  - source ./.travis/install.sh

before_script:
  - export TEST_BAUD_RATE=1200

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then make style_check; fi
  - make test ARGS="-i=${TEST_INPUT_PTY} -o=${TEST_OUTPUT_PTY} -b=${TEST_BAUD_RATE}"
  - bash ./.travis/check.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
